services:
  caddy:
    image: caddy:latest
    container_name: caddy
    network_mode: host
    restart: always
    #environment:
    #  - ACME_AGREE=true          
    #  - CLOUDFLARE_API_TOKEN=xxxx
    cap_add:
      - NET_ADMIN
    #ports:
    #  - "80:80"
    #  - "443:443"
    #  - "443:443/udp"
    volumes:
      - ./conf:/etc/caddy
      #- ./site:/srv
      - ./caddy_data:/data
      #- ./caddy_config:/config
