services:
  tao-sync: 
    image: dr34m/tao-sync:latest
    container_name: tao-sync
    ports: 
      - 8023:8023
    volumes: 
      - ./data:/app/data
    restart: always    
    network_mode: bridge
