services:
  pansou:
    image: ghcr.io/fish2018/pansou-web:latest
    container_name: pansou
    restart: always
    ports:
      - "7080:80"
    environment:
      # 如果 SOCKS5 没有用户名密码
      PROXY: "socks5://127.0.0.1:1080"
      # 如果 SOCKS5 有用户名密码，示例：
      # PROXY: "socks5://user:pass@127.0.0.1:1080"
      #AUTH_ENABLED: "true"
      #AUTH_USERS: "admin:admin,viewer:viewer"
      #AUTH_TOKEN_EXPIRY: "168" 
      #AUTH_JWT_SECRET:   #openssl rand -base64 32
    volumes:
      - ./pansou-data:/app/data
